### ISSUE TITLE
Creating A Transaction

### ISSUE THREAD

**Issue by johnzengin** [dart-bitcoin/bitcoin_flutter#33]
I need to make a transaction with bitcoin_flutter is it possible to make transaction from one wallet to another and if it is is there a function to make it simply transaction(pubKey,prvtKey,amount).

**Comment by longhoangwkm** [comment]
Sadly, it impossible. you are mentioning about the simplest case. For some special cases like p2sh, p2wsh. that's not enough information to create a transaction
