### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by RohanKapurDEV** [dart-bitcoin/bitcoin_flutter#40]
Was wondering if this library is still being worked on? Seems to be a little quiet in the repo

**Comment by Dolaned** [comment]
also wondering this and would like to perhaps make this into an spv wallet?

**Comment by RohanKapurDEV** [comment]
Would be interesting. I'm more concerned with the addition of things like PSBT, MultiSig Native Segwit address generation for now though. But adding in SPV functionality couldn't hurt I guess

**Comment by Dolaned** [comment]
I think it could be helpful would you be interested in working on it with me. ?

**Comment by brunocalmels** [comment]
> I think it could be helpful would you be interested in working on it with me. ?

Hey guys! I'm in a team and there's 3 of us with hands to collaborate.

Our first issue to tackle would be to be able to use P2PKH along with witness inputs in a single transaction, which seems to be troublesome right now.

What about you?

**Comment by longhoangwkm** [comment]
We don't have resources to develop, we look forward to the contributions from everyone

**Comment by vmenond** [comment]
I would like to team up with someone to work on this project.
@brunocalmels  @Dolaned  @RohanKapurDEV

**Comment by dragonDScript** [comment]
> We don't have resources to develop now, we look forward to the contributions from everyone

I'm looking to help you financially. I don't have much money but I think I can help! please let me know if you're interested via telegram @aitor_gt
