### ISSUE TITLE
Sending to and validation P2SH addresses.

### ISSUE THREAD

**Issue by baahkusi** [dart-bitcoin/bitcoin_flutter#51]
Hi, thanks for your great work on the library. Currently I do seem to get `Invalid version or network mismatch error` whenever I use P2SH addresses starting with `3`.  I'm able to send to legacy and native segwit addresses. Does the library support sending to P2SH addresses starting with `3`?

**Comment by SFzxc** [comment]
Yes, This lib currently only support  legacy and native segwit addresses. PR are welcome to ssupport P2SH address
